import { mkdir, readFile, stat, writeFile } from 'node:fs/promises'
import { basename, dirname, relative, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDir = dirname(fileURLToPath(import.meta.url))
const webuiRoot = resolve(scriptDir, '..')
const generatedDir = resolve(webuiRoot, '.generated')
const outputPath = resolve(generatedDir, 'fonts.css')

// Preserve Fontsource's unicode-range faces so the browser downloads only the Noto glyph
// slices needed by the current page. Keep WOFF2 only: all supported browsers use it, while
// shipping Fontsource's WOFF fallback nearly doubles the embedded font payload.
const packages = [
  { name: '@fontsource/ibm-plex-sans', entries: ['latin-400.css', 'latin-500.css'], minFaces: 1 },
  { name: '@fontsource/ibm-plex-mono', entries: ['latin-400.css', 'latin-500.css'], minFaces: 1 },
  { name: '@fontsource/noto-sans-sc', entries: ['400.css', '500.css'], minFaces: 90, requireUnicodeRanges: true },
]

const output = [
  '/* Generated by scripts/generate-fonts.mjs. Do not edit by hand. */',
  '/* Unicode-range subsets are retained; legacy WOFF sources are intentionally omitted. */',
]
let faceCount = 0
let totalWoff2Bytes = 0

for (const fontPackage of packages) {
  for (const entry of fontPackage.entries) {
    const packageCssPath = resolve(webuiRoot, 'node_modules', fontPackage.name, entry)
    const css = await readFile(packageCssPath, 'utf8')
    const faces = css.match(/@font-face\s*\{[^}]*\}/g) ?? []
    if (faces.length < fontPackage.minFaces) {
      throw new Error(`${fontPackage.name}/${entry}: found ${faces.length} @font-face blocks; expected at least ${fontPackage.minFaces}`)
    }

    for (const face of faces) {
      const src = face.match(/\bsrc\s*:\s*([^;]+);/i)?.[1]
      if (!src) throw new Error(`${fontPackage.name}/${entry}: @font-face is missing src`)
      const woff2Sources = [...src.matchAll(/url\(([^)]+)\)\s*format\(['"]woff2['"]\)/gi)]
      if (woff2Sources.length !== 1) {
        throw new Error(`${fontPackage.name}/${entry}: expected exactly one WOFF2 source per face, got ${woff2Sources.length}`)
      }
      if (fontPackage.requireUnicodeRanges && !/\bunicode-range\s*:/i.test(face)) {
        throw new Error(`${fontPackage.name}/${entry}: Noto face is missing unicode-range`)
      }

      const sourcePath = woff2Sources[0][1].trim().replace(/^['"]|['"]$/g, '')
      const filename = basename(sourcePath)
      const fontFilePath = resolve(webuiRoot, 'node_modules', fontPackage.name, 'files', filename)
      const fontFileStat = await stat(fontFilePath).catch(() => undefined)
      if (!fontFileStat?.isFile()) {
        throw new Error(`${fontPackage.name}/${entry}: missing WOFF2 file ${filename}`)
      }
      totalWoff2Bytes += fontFileStat.size

      // Output lives at webui/.generated/fonts.css, so route Vite to the package's real file.
      const relativeFontPath = relative(generatedDir, fontFilePath).split(sep).join('/')
      const rewritten = face.replace(
        /\bsrc\s*:\s*[^;]+;/i,
        `src: url("${relativeFontPath}") format("woff2");`,
      )
      output.push(rewritten)
      faceCount++
    }
  }
}

await mkdir(generatedDir, { recursive: true })
await writeFile(outputPath, `${output.join('\n')}\n`, 'utf8')
console.log(`generated ${faceCount} WOFF2-only font faces (${(totalWoff2Bytes / 1048576).toFixed(2)} MB available, unicode-range slicing retained)`)
