import { readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDir = dirname(fileURLToPath(import.meta.url))
const webuiRoot = resolve(scriptDir, '..')
const outputPath = resolve(webuiRoot, 'src/lib/icons.ts')

// The console ships its own icon glyphs instead of generating Iconify CSS classes:
// the CSP allows no cross-origin connect, so an icon that is not in the bundle can
// only fail silently by falling back to the public API.
const collections = [
  {
    name: 'heroicons',
    icons: [
      'arrow-down',
      'arrow-left-on-rectangle',
      'arrow-path',
      'arrow-path-rounded-square',
      'arrow-up',
      'arrow-up-tray',
      'bars-3',
      'check',
      'check-circle',
      'chevron-down',
      'chevron-left',
      'chevron-right',
      'chevron-up',
      'chevron-up-down',
      'circle-stack',
      'clipboard-document',
      'clock',
      'cog-6-tooth',
      'cpu-chip',
      'document-text',
      'exclamation-circle',
      'exclamation-triangle',
      'eye',
      'eye-slash',
      'information-circle',
      'key',
      'lock-closed',
      'magnifying-glass',
      'no-symbol',
      'pencil-square',
      'plus',
      'queue-list',
      'server-stack',
      'squares-2x2',
      'trash',
      'user',
      'wrench-screwdriver',
      'x-mark',
    ],
  },
  {
    name: 'lucide',
    // Kept from the previous markup so existing iconography does not shift.
    icons: ['circle-check', 'gauge', 'layers-2', 'moon', 'sun'],
  },
]

const glyphs = []

for (const collection of collections) {
  const collectionPath = resolve(webuiRoot, 'node_modules', `@iconify-json/${collection.name}`, 'icons.json')
  const parsed = JSON.parse(await readFile(collectionPath, 'utf8'))
  const defaultWidth = parsed.width ?? 24
  const defaultHeight = parsed.height ?? 24

  for (const name of collection.icons) {
    const entry = parsed.icons?.[name] ?? parsed.aliases?.[name]
    if (!entry?.body) throw new Error(`@iconify-json/${collection.name}: "${name}" is not in this version`)
    const parent = parsed.icons?.[name] ? undefined : parsed.icons?.[entry.parent]
    const body = entry.body ?? parent?.body
    if (!body) throw new Error(`@iconify-json/${collection.name}: "${name}" has no SVG body`)
    if (/url\(|<image|<script/i.test(body)) throw new Error(`@iconify-json/${collection.name}: "${name}" is not a plain path glyph`)

    // Every glyph is 24x24 in these two collections; resolve an explicit size when one differs.
    const width = entry.width ?? parent?.width ?? defaultWidth
    const height = entry.height ?? parent?.height ?? defaultHeight
    glyphs.push({ name, viewBox: `0 0 ${width} ${height}`, body })
  }
}

const seen = new Set()
for (const glyph of glyphs) {
  if (seen.has(glyph.name)) throw new Error(`duplicate icon name across collections: ${glyph.name}`)
  seen.add(glyph.name)
}

const lines = [
  '/* Generated by scripts/generate-icons.mjs. Do not edit by hand. */',
  '/* Rendered by components/JfIcon.vue as inline SVG using currentColor. */',
  'export interface JfIconGlyph {',
  '  viewBox: string',
  '  body: string',
  '}',
  '',
  'export const icons = {',
  ...glyphs.map((glyph) => `  ${JSON.stringify(glyph.name)}: { viewBox: ${JSON.stringify(glyph.viewBox)}, body: ${JSON.stringify(glyph.body)} },`),
  '} as const',
  '',
  'export type IconName = keyof typeof icons',
  '',
]

await writeFile(outputPath, lines.join('\n'), 'utf8')
console.log(`generated ${glyphs.length} icon glyphs into src/lib/icons.ts`)
