// Package jev adapts the TypeSafe System One API ("Jev") to a small, testable
// contract: the caller declares the candidate models and their capabilities,
// the client maps them onto the verified wire format, performs exactly one HTTP
// call, and returns a strictly validated, normalized result.
//
// The package deliberately depends on none of the router's other layers: it
// takes plain data structures and returns plain data structures, so it can be
// exercised by its own tests and replaced without touching policy or
// transport code.
//
// Wire contract verified on 2026-09-21 against the official TypeSafe OpenAPI
// schema and SDK (see testdata/README.md). It never retries: a routed decision
// is cheap to repeat for the caller, but a duplicated call is a duplicated
// billable evaluation.
package jev

import (
	"bytes"
	"context"
	"crypto/tls"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"math"
	"net"
	"net/http"
	"net/url"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/nextroad-dev/Auto-Router/internal/models"
	"github.com/nextroad-dev/Auto-Router/internal/providers"
)

// Fixed protocol and transport constants. They are not configurable: the
// endpoint path, the question id the routing question is sent under, and the
// bounds that keep a malformed response from exhausting memory are part of the
// verified contract, not deployment knobs.
const (
	// systemOnePath is the single System One endpoint.
	systemOnePath = "/v1/systemone"
	// routeQuestionID is the question id the route request is sent under. The
	// id is not shown to the model, so a stable literal is enough.
	routeQuestionID = "routed_model"
	// maxResponseBytes bounds a Jev response body. A valid answer set is a few
	// kilobytes; the limit exists so a hostile or broken peer cannot stream
	// unbounded data into memory.
	maxResponseBytes = 1 << 20
	// maxRequestBytes bounds the encoded request body. It is generous enough
	// for a full conversation with tools, and bounded so a pathological input
	// cannot exhaust memory.
	maxRequestBytes = 4 << 20
	// maxCandidates is the largest candidate set one routing question may
	// carry. The verified official Choice primitive accepts at most 255
	// options, so a larger request could only ever be rejected upstream; a
	// caller mistake is reported as ErrInvalidRequest instead of being turned
	// into an upstream 4xx.
	maxCandidates = 255
	// probabilityEpsilon is the accepted deviation of the returned
	// distribution from exactly 1.0. Values inside the tolerance are accepted
	// and normalized; anything larger rejects the whole result.
	probabilityEpsilon = 1e-6
	// maxErrorSummaryBytes bounds the sanitized upstream error excerpt that a
	// returned error may carry.
	maxErrorSummaryBytes = 200

	// dialKeepAlive mirrors net.Dialer's default.
	dialKeepAlive = 30 * time.Second
	// tlsHandshakeTimeout bounds the TLS setup of one call.
	tlsHandshakeTimeout = 10 * time.Second
	// idleConnTimeout releases pooled connections so a decision client does
	// not hold sockets open between sporadic routing calls.
	idleConnTimeout = 90 * time.Second
)

// InputMode selects how much of the client's conversation is sent to Jev. It is
// a router-side privacy control: the wire format is unchanged, the caller simply
// decides what to put in SystemPrompt and Messages. The three modes are
// orthogonal to jev.enabled: "Jev is on" and "Jev may see the conversation" are
// two separate decisions.
type InputMode string

const (
	// InputModeContent sends the analyzer's conversation view verbatim. It is
	// the default, and it is the mode that makes the recommendation as
	// well-informed as possible at the cost of sending the prompt off-process.
	InputModeContent InputMode = "content"
	// InputModeRedacted sends the same view after deterministic, best-effort
	// redaction: URLs, email addresses, inline data URIs, token-shaped and
	// long high-entropy strings are replaced, and each text block is cut to a
	// bounded UTF-8-safe excerpt. This is a reduction of what leaves the
	// process, not an anonymization guarantee: there is no entity recognition
	// and no external dependency, and the caller is told so.
	InputModeRedacted InputMode = "redacted"
	// InputModeFeaturesOnly sends no client text at all: SystemPrompt is empty,
	// Tools is empty, and the single message is generated by the router from
	// counts and enumerations.
	InputModeFeaturesOnly InputMode = "features_only"
)

// inputModeOrder fixes the order the modes are listed in, so an error message
// never depends on map iteration.
var inputModeOrder = []InputMode{InputModeContent, InputModeRedacted, InputModeFeaturesOnly}

// InputModeValues lists the accepted modes in a fixed order. It exists so the
// configuration validator and the error messages describe the same closed set.
func InputModeValues() []string {
	values := make([]string, 0, len(inputModeOrder))
	for _, mode := range inputModeOrder {
		values = append(values, string(mode))
	}
	return values
}

// Valid reports whether the mode is one of the three accepted values.
func (m InputMode) Valid() bool {
	for _, candidate := range inputModeOrder {
		if m == candidate {
			return true
		}
	}
	return false
}

// ParseInputMode accepts exactly one of the three literals. Like the routing
// preference, the value is not normalized: a configuration file that says
// "Redacted" is a typo to fix, not an input to interpret. The error lists the
// accepted values and never repeats the offending text.
func ParseInputMode(value string) (InputMode, error) {
	for _, candidate := range inputModeOrder {
		if InputMode(value) == candidate {
			return candidate, nil
		}
	}
	return "", inputModeError()
}

// Errors are the stable classifications callers branch on. Every failure
// returned by Route wraps exactly one of these sentinels, so callers can use
// errors.Is instead of matching strings. No error ever contains the API key.
var (
	// ErrNotConfigured means the client was called without a usable
	// configuration. Callers map it onto an explicit 503 rather than a retry.
	ErrNotConfigured = errors.New("jev client is not configured")
	// ErrInvalidRequest means the caller supplied an unusable request: no
	// candidates, unknown protocol, oversized body. It is a programming error
	// and must not trigger fallback.
	ErrInvalidRequest = errors.New("invalid jev request")
	// ErrTimeout means the call exceeded the configured timeout.
	ErrTimeout = errors.New("jev request timed out")
	// ErrCanceled means the caller's context was canceled, typically because
	// the client disconnected or the process is shutting down.
	ErrCanceled = errors.New("jev request canceled")
	// ErrUnavailable means the endpoint could not be reached or reported a
	// temporary failure (connection/TLS errors, 408, 429, 5xx).
	ErrUnavailable = errors.New("jev endpoint unavailable")
	// ErrRejected means the endpoint refused the request itself: an
	// authentication, permission or validation failure. Retrying cannot help.
	ErrRejected = errors.New("jev request rejected")
	// ErrInvalidResponse means a 2xx response could not be parsed as the
	// verified JSON shape.
	ErrInvalidResponse = errors.New("invalid jev response")
	// ErrInvalidResult means the response parsed but failed strict validation:
	// an unknown candidate, a missing/negative/non-finite probability, a
	// duplicated candidate, or a distribution that does not sum to 1.
	ErrInvalidResult = errors.New("invalid jev result")
)

// Candidate is one model the caller is willing to route to, together with the
// capabilities the caller has already resolved for it. This package never
// merges capabilities across providers or infers them: the caller (stage 6/7)
// owns that decision, and the client only forwards what it is told.
type Candidate struct {
	// Model is the logical model identifier from the registry.
	Model string
	// ContextWindow is the usable context size in tokens.
	ContextWindow int
	// MaxOutput is the maximum output size, when known.
	MaxOutput *int
	// SupportsTools, SupportsVision and SupportsReasoning mirror the registry
	// capability flags; a zero value means "not supported".
	SupportsTools     bool
	SupportsVision    bool
	SupportsReasoning bool
	// Description optionally replaces the derived capability summary shown next to
	// the model name in the routing question. A caller that combines several
	// providers into one candidate uses it to state what the combined entry
	// actually guarantees (for example a conservative capability envelope); an
	// empty value keeps the derived summary, which describes this candidate's own
	// fields exactly.
	Description string
}

// Request is one routing decision request.
type Request struct {
	// Protocol labels which client API the conversation arrived on. It is sent
	// as context so the recommendation can account for the protocol's
	// capabilities.
	Protocol providers.Protocol
	// Candidates is the non-empty, duplicate-free set of models the caller
	// allows. Order is preserved in the request; the result is sorted.
	Candidates []Candidate
	// Messages is the conversation exactly as the client sent it. It is
	// forwarded verbatim: rewriting the prompt would change what the model
	// judges. The configured input mode controls what reaches this client.
	Messages []Message
	// SystemPrompt, when non-empty, mirrors the client's system instruction.
	SystemPrompt string
	// Tools lists the tool names the client offered. Only the names are sent:
	// the routing question is about capability, not about tool schemas.
	Tools []string
}

// Message is one conversation turn forwarded to Jev without rewriting.
type Message struct {
	Role    string `json:"role"`
	Content any    `json:"content"`
}

// CandidateProbability is the normalized probability of one candidate.
type CandidateProbability struct {
	Model       string
	Probability float64
}

// RawIO carries the exact request and response bytes of one call. It is only
// populated when capture_raw_io is enabled, because the request body contains
// the client's prompt text. Callers decide where (if anywhere) it may be
// stored; this package never logs or persists it.
type RawIO struct {
	Request  []byte
	Response []byte
}

// Result is a validated, normalized routing recommendation.
type Result struct {
	// Selected is the model the endpoint recommends. It always belongs to the
	// candidate set.
	Selected string
	// Probabilities covers every candidate, sorted by descending probability
	// and then by ascending model id, and sums to exactly 1.0 in float64
	// arithmetic. Ties are therefore deterministic.
	Probabilities []CandidateProbability
	// Confidence is the endpoint's confidence for the selection when it
	// reports one, otherwise the normalized probability of Selected. It is
	// always finite and within [0, 1].
	Confidence float64
	// Raw is set only when the client was configured to capture raw I/O.
	Raw *RawIO
}

// Config is the resolved client configuration. It is copied from the process
// configuration at composition time so this package depends on neither the
// configuration loader nor the HTTP layer.
type Config struct {
	// BaseURL is the TypeSafe API root, for example https://api.typesafe.ai.
	// Its path is preserved as a prefix.
	BaseURL string
	// APIKey is the TypeSafe bearer token. Empty means "send no credential",
	// which validation only permits for a loopback endpoint.
	APIKey string
	// Model is the pinned System One model name. It is required.
	Model string
	// AuthHeader and AuthScheme describe how the token is transmitted.
	AuthHeader string
	AuthScheme string
	// Timeout bounds one complete call, including the response body read.
	Timeout time.Duration
	// CaptureRawIO keeps the raw request and response bytes in the Result.
	CaptureRawIO bool
	// InputMode selects how much of the conversation the caller sends. It is
	// validated but never interpreted here: the orchestrator builds the request
	// body, and this package only refuses a mode it does not know.
	InputMode InputMode
}

// Client is a ready-to-use System One client. It is safe for concurrent use:
// it holds only immutable configuration and an *http.Client.
type Client struct {
	client       *http.Client
	endpoint     *url.URL
	apiKey       string
	model        string
	authHeader   string
	authValue    string
	timeout      time.Duration
	captureRawIO bool
}

// New validates the configuration and builds the HTTP client. It fails on a
// malformed endpoint instead of deferring the error to the first routing call,
// so a typo surfaces at startup.
func New(cfg Config) (*Client, error) {
	if cfg.BaseURL == "" {
		return nil, fmt.Errorf("%w: base URL is empty", ErrNotConfigured)
	}
	endpoint, err := url.Parse(cfg.BaseURL)
	if err != nil || endpoint.Host == "" {
		return nil, fmt.Errorf("%w: base URL must be an absolute http(s) URL", ErrNotConfigured)
	}
	if endpoint.Scheme != "http" && endpoint.Scheme != "https" {
		return nil, fmt.Errorf("%w: base URL must use the http or https scheme", ErrNotConfigured)
	}
	if endpoint.Scheme == "http" && !models.IsLoopbackHost(endpoint.Hostname()) {
		return nil, fmt.Errorf("%w: base URL must use https unless the host is loopback", ErrNotConfigured)
	}
	if err := validateModelName(cfg.Model); err != nil {
		return nil, fmt.Errorf("%w: %v", ErrNotConfigured, err)
	}
	// An empty mode means "the caller did not set one", which is the content
	// mode: a client built programmatically keeps working. An unknown non-empty
	// mode is refused so a typo cannot silently degrade to a different
	// privacy/decision trade-off.
	inputMode := cfg.InputMode
	if inputMode == "" {
		inputMode = InputModeContent
	}
	if _, err := ParseInputMode(string(inputMode)); err != nil {
		return nil, fmt.Errorf("%w: %v", ErrNotConfigured, err)
	}
	if cfg.Timeout <= 0 {
		return nil, fmt.Errorf("%w: timeout must be positive", ErrNotConfigured)
	}
	if cfg.AuthHeader == "" {
		return nil, fmt.Errorf("%w: auth header must be set", ErrNotConfigured)
	}
	transport := &http.Transport{
		Proxy: http.ProxyFromEnvironment,
		DialContext: (&net.Dialer{
			Timeout:   cfg.Timeout,
			KeepAlive: dialKeepAlive,
		}).DialContext,
		ForceAttemptHTTP2:     true,
		MaxIdleConns:          8,
		MaxIdleConnsPerHost:   8,
		IdleConnTimeout:       idleConnTimeout,
		TLSHandshakeTimeout:   tlsHandshakeTimeout,
		ExpectContinueTimeout: time.Second,
		// The whole call is bounded by the request context, so the transport
		// needs no response header timeout of its own.
		DisableCompression: true,
		TLSClientConfig:    &tls.Config{MinVersion: tls.VersionTLS12},
	}
	return &Client{
		// No Client.Timeout: the deadline is applied to the request context so
		// the caller's own cancellation composes with it instead of being
		// replaced.
		client:       &http.Client{Transport: transport},
		endpoint:     endpoint,
		apiKey:       cfg.APIKey,
		model:        cfg.Model,
		authHeader:   cfg.AuthHeader,
		authValue:    authValue(cfg.AuthScheme, cfg.APIKey),
		timeout:      cfg.Timeout,
		captureRawIO: cfg.CaptureRawIO,
	}, nil
}

// inputModeError is the shared error for an unusable input mode. It lists the
// accepted literals and repeats nothing the caller sent.
func inputModeError() error {
	return fmt.Errorf("input mode must be one of %s", strings.Join(InputModeValues(), ", "))
}

// CloseIdleConnections releases pooled connections. The composition root calls
// it during shutdown so the process exits without waiting for idle sockets.
func (c *Client) CloseIdleConnections() {
	if c == nil {
		return
	}
	if transport, ok := c.client.Transport.(*http.Transport); ok {
		transport.CloseIdleConnections()
	}
}

// Route performs exactly one System One call and returns the validated result.
func (c *Client) Route(ctx context.Context, request Request) (Result, error) {
	if c == nil {
		return Result{}, fmt.Errorf("%w: no client", ErrNotConfigured)
	}
	body, err := c.buildRequest(request)
	if err != nil {
		return Result{}, err
	}
	callCtx, cancel := context.WithTimeout(ctx, c.timeout)
	defer cancel()
	upstream, err := c.newHTTPRequest(callCtx, body)
	if err != nil {
		return Result{}, err
	}
	response, err := c.client.Do(upstream)
	if err != nil {
		return Result{}, classifyTransport(ctx, callCtx, err)
	}
	defer response.Body.Close()
	// Headers arrived, so the call itself succeeded; a read failure after this
	// point is reported as a response problem, not as a transport failure.
	payload, readErr := readBounded(response.Body, maxResponseBytes)
	if readErr != nil {
		if ctxErr := ctx.Err(); ctxErr != nil {
			return Result{}, fmt.Errorf("%w: %v", ErrCanceled, ctxErr)
		}
		if callCtx.Err() != nil {
			return Result{}, fmt.Errorf("%w: %v", ErrTimeout, callCtx.Err())
		}
		return Result{}, fmt.Errorf("%w: response body could not be read (%v)", ErrInvalidResponse, readErr)
	}
	if response.StatusCode < 200 || response.StatusCode > 299 {
		return Result{}, statusError(response.StatusCode, payload, c.apiKey)
	}
	answers, err := decodeResponse(payload)
	if err != nil {
		return Result{}, err
	}
	result, err := normalize(answers, request.Candidates)
	if err != nil {
		return Result{}, err
	}
	if c.captureRawIO {
		result.Raw = &RawIO{Request: body, Response: payload}
	}
	return result, nil
}

// buildRequest validates the caller's input and encodes the verified request
// shape. Validation here is a programming-error gate: everything it rejects
// indicates a caller bug rather than an upstream problem.
func (c *Client) buildRequest(request Request) ([]byte, error) {
	if !request.Protocol.Valid() {
		return nil, fmt.Errorf("%w: protocol must be %q or %q", ErrInvalidRequest, providers.ProtocolChatCompletions, providers.ProtocolResponses)
	}
	if len(request.Candidates) == 0 {
		return nil, fmt.Errorf("%w: at least one candidate is required", ErrInvalidRequest)
	}
	if len(request.Messages) == 0 {
		// The state is what the questions are asked about; without it the
		// recommendation would be made on capability alone. A caller that has no
		// conversation has nothing to route yet, and sending an empty state
		// would spend a billable evaluation on a meaningless question.
		return nil, fmt.Errorf("%w: at least one conversation message is required", ErrInvalidRequest)
	}
	if len(request.Candidates) > maxCandidates {
		return nil, fmt.Errorf("%w: at most %d candidates are supported, got %d", ErrInvalidRequest, maxCandidates, len(request.Candidates))
	}
	seen := make(map[string]struct{}, len(request.Candidates))
	for index, candidate := range request.Candidates {
		if err := validateCandidate(candidate); err != nil {
			return nil, fmt.Errorf("%w: candidate[%d]: %v", ErrInvalidRequest, index, err)
		}
		if _, duplicate := seen[candidate.Model]; duplicate {
			return nil, fmt.Errorf("%w: candidate %q appears more than once", ErrInvalidRequest, candidate.Model)
		}
		seen[candidate.Model] = struct{}{}
	}
	payload := c.encode(request)
	encoded, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("%w: request could not be encoded", ErrInvalidRequest)
	}
	if len(encoded) > maxRequestBytes {
		return nil, fmt.Errorf("%w: request body exceeds %d bytes", ErrInvalidRequest, maxRequestBytes)
	}
	return encoded, nil
}

// newHTTPRequest builds the outbound call. Only the fields the verified
// contract needs are set: a client credential from elsewhere is never
// forwarded, and the transport owns body framing.
func (c *Client) newHTTPRequest(ctx context.Context, body []byte) (*http.Request, error) {
	upstream := *c.endpoint
	upstream.Path = joinPath(c.endpoint.Path, systemOnePath)
	if c.endpoint.RawPath != "" {
		upstream.RawPath = joinPath(c.endpoint.RawPath, systemOnePath)
	}
	upstream.RawQuery = ""
	upstream.ForceQuery = false
	request, err := http.NewRequestWithContext(ctx, http.MethodPost, upstream.String(), bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("%w: %v", ErrInvalidRequest, err)
	}
	request.Header.Set("Content-Type", "application/json")
	request.Header.Set("Accept", "application/json")
	request.Header.Set("Accept-Encoding", "identity")
	request.Header.Set("User-Agent", "auto-router/1")
	if c.authValue != "" {
		request.Header.Set(c.authHeader, c.authValue)
	} else {
		request.Header.Del(c.authHeader)
	}
	return request, nil
}

// readBounded reads at most limit bytes and reports an error when the body is
// longer, so a misbehaving peer cannot force an unbounded allocation.
func readBounded(body io.Reader, limit int64) ([]byte, error) {
	payload, err := io.ReadAll(io.LimitReader(body, limit+1))
	if err != nil {
		return nil, err
	}
	if int64(len(payload)) > limit {
		return nil, fmt.Errorf("response exceeds %d bytes", limit)
	}
	return payload, nil
}

// authValue renders the credential for the configured header. An empty key
// yields an empty value, which the caller treats as "send no credential".
func authValue(scheme, key string) string {
	if key == "" {
		return ""
	}
	if scheme == "" {
		return key
	}
	return scheme + " " + key
}

// joinPath concatenates a base path prefix with a fixed suffix without
// producing a double slash or dropping the prefix.
func joinPath(prefix, suffix string) string {
	switch {
	case prefix == "" || prefix == "/":
		return suffix
	case strings.HasSuffix(prefix, "/"):
		return prefix + strings.TrimPrefix(suffix, "/")
	default:
		return prefix + suffix
	}
}

// classifyTransport maps a transport failure onto the contract's sentinels.
// The caller's context is checked first: a client disconnect is not an upstream
// outage, and reporting it as one would trigger pointless fallback.
func classifyTransport(outer, call context.Context, err error) error {
	if ctxErr := outer.Err(); ctxErr != nil {
		return fmt.Errorf("%w: %v", ErrCanceled, ctxErr)
	}
	if call.Err() != nil || errors.Is(err, context.DeadlineExceeded) {
		return fmt.Errorf("%w: %v", ErrTimeout, err)
	}
	if errors.Is(err, context.Canceled) {
		return fmt.Errorf("%w: %v", ErrCanceled, err)
	}
	var netErr net.Error
	if errors.As(err, &netErr) && netErr.Timeout() {
		return fmt.Errorf("%w: %v", ErrTimeout, err)
	}
	return fmt.Errorf("%w: %v", ErrUnavailable, err)
}

// statusError classifies a non-2xx response. Temporary conditions ask the
// caller to consider fallback; a refused request is a configuration or
// credential problem that retrying cannot fix. secret is redacted from the
// summary: an endpoint that echoes a credential back must not be able to push
// it into a log.
func statusError(status int, body []byte, secret string) error {
	summary := errorSummary(body, secret)
	switch {
	case status == http.StatusRequestTimeout || status == http.StatusTooManyRequests || status >= 500:
		return newStatusError(ErrUnavailable, status, summary)
	default:
		return newStatusError(ErrRejected, status, summary)
	}
}

// statusFailure carries the HTTP status and a bounded, sanitized excerpt of the
// upstream error body. The excerpt never contains the API key, and it is
// truncated and stripped of control characters before it can reach a log.
type statusFailure struct {
	sentinel error
	status   int
	summary  string
}

func newStatusError(sentinel error, status int, summary string) error {
	return &statusFailure{sentinel: sentinel, status: status, summary: summary}
}

func (e *statusFailure) Error() string {
	if e.summary == "" {
		return fmt.Sprintf("%v: status %d", e.sentinel, e.status)
	}
	return fmt.Sprintf("%v: status %d: %s", e.sentinel, e.status, e.summary)
}

// Unwrap exposes the sentinel so callers keep using errors.Is.
func (e *statusFailure) Unwrap() error { return e.sentinel }

// Status returns the HTTP status the endpoint answered with.
func (e *statusFailure) Status() int { return e.status }

// Summary returns the sanitized excerpt of the upstream error body.
func (e *statusFailure) Summary() string { return e.summary }

// errorSummary extracts a short, printable excerpt from an error body. The
// preferred source is the documented validation shape ("detail"[].msg); falling
// back to the raw bytes is safe because the excerpt is bounded, stripped of
// control characters, and has any credential redacted. secret is the
// configured token, which is removed even when the endpoint echoes it back.
func errorSummary(body []byte, secret string) string {
	body = bytes.TrimSpace(body)
	if len(body) == 0 {
		return ""
	}
	var envelope struct {
		// Detail is the documented validation shape, an array of {loc, msg,
		// type}; some servers use a plain string instead.
		Detail json.RawMessage `json:"detail"`
		// Error may be a string or an object with a message.
		Error   json.RawMessage `json:"error"`
		Message string          `json:"message"`
	}
	if err := json.Unmarshal(body, &envelope); err == nil {
		if detail := validationMessages(envelope.Detail); detail != "" {
			return redact(sanitize(detail), secret)
		}
		if envelope.Message != "" {
			return redact(sanitize(envelope.Message), secret)
		}
		if text := anyMessage(envelope.Error); text != "" {
			return redact(sanitize(text), secret)
		}
	}
	return redact(sanitize(string(body)), secret)
}

// validationMessages renders a "detail" value: either the documented array of
// {loc, msg, type} entries or a plain string.
func validationMessages(raw json.RawMessage) string {
	if len(raw) == 0 {
		return ""
	}
	var entries []struct {
		Message string `json:"msg"`
	}
	if json.Unmarshal(raw, &entries) == nil && len(entries) > 0 {
		parts := make([]string, 0, len(entries))
		for _, entry := range entries {
			if entry.Message != "" {
				parts = append(parts, entry.Message)
			}
		}
		return strings.Join(parts, "; ")
	}
	return anyMessage(raw)
}

// anyMessage renders a JSON value that is either a string or an object with a
// "message" field.
func anyMessage(raw json.RawMessage) string {
	if len(raw) == 0 {
		return ""
	}
	var text string
	if json.Unmarshal(raw, &text) == nil {
		return text
	}
	var envelope struct {
		Message string `json:"message"`
	}
	if json.Unmarshal(raw, &envelope) == nil {
		return envelope.Message
	}
	return ""
}

// redactedSecret is the replacement for any credential that would otherwise
// appear in a message leaving this package.
const redactedSecret = "[redacted]"

// redact removes the configured credential from a message. It never returns the
// secret, and short secrets are still replaced: a leak is a leak regardless of
// length.
func redact(message, secret string) string {
	if secret == "" || message == "" {
		return message
	}
	return strings.ReplaceAll(message, secret, redactedSecret)
}

// sanitize removes control characters and bounds the length of a message that
// may have originated upstream. The bound counts bytes but is only applied
// between runes, so the result is always valid UTF-8 for a log or JSON handler.
func sanitize(raw string) string {
	var builder strings.Builder
	builder.Grow(len(raw))
	for _, r := range raw {
		if r < 0x20 || r == 0x7f {
			r = ' '
		}
		// Check before writing: a rune is at most 4 bytes, so the result can
		// overshoot by at most 3 bytes but never split a rune.
		if builder.Len()+utf8.RuneLen(r) > maxErrorSummaryBytes {
			break
		}
		builder.WriteRune(r)
	}
	return strings.TrimSpace(builder.String())
}

// validateModelName mirrors the configuration check so a programmatically built
// client cannot bypass the model identifier syntax constraints. Upstream aliases
// are allowed and sent through unchanged.
func validateModelName(model string) error {
	if model == "" {
		return errors.New("model is empty")
	}
	if model != strings.TrimSpace(model) {
		return errors.New("model must not be padded with whitespace")
	}
	if strings.ContainsRune(model, '\x00') {
		return errors.New("model must not contain NUL")
	}
	return nil
}

// validateCandidate checks one caller-declared candidate.
func validateCandidate(candidate Candidate) error {
	if candidate.Model == "" {
		return errors.New("model must not be empty")
	}
	if candidate.Model != strings.TrimSpace(candidate.Model) {
		return errors.New("model must not be padded with whitespace")
	}
	if strings.ContainsRune(candidate.Model, '\x00') {
		return errors.New("model must not contain NUL")
	}
	if candidate.ContextWindow <= 0 {
		return errors.New("context_window must be positive")
	}
	if candidate.MaxOutput != nil && (*candidate.MaxOutput <= 0 || *candidate.MaxOutput > candidate.ContextWindow) {
		return errors.New("max_output must be greater than zero and at most context_window")
	}
	return nil
}

// sortedProbabilities orders the normalized distribution deterministically:
// descending probability, then ascending model id. Two candidates can never
// share a model id, so the order is total.
func sortedProbabilities(values []CandidateProbability) {
	sort.Slice(values, func(i, j int) bool {
		if values[i].Probability != values[j].Probability {
			return values[i].Probability > values[j].Probability
		}
		return values[i].Model < values[j].Model
	})
}

// finite reports whether value is a real number, rejecting NaN and infinities.
func finite(value float64) bool {
	return !math.IsNaN(value) && !math.IsInf(value, 0)
}
